name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest           # GitHub-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}   # usually root
          key:      ${{ secrets.PROD_SSH_KEY }}    # private key
          script: |
            set -euo pipefail
            REPO=/root/ravitracker-mdt

            git -C "$REPO" fetch origin main
            git -C "$REPO" reset --hard origin/main
            git -C "$REPO" clean -fdx
            git -C "$REPO" config --local core.filemode false

            # Normalize line endings just in case
            sed -i 's/\r$//' "$REPO/scripts/deploy-ravitracker.sh"

            # Run via bash so +x isn’t required to succeed
            bash "$REPO/scripts/deploy-ravitracker.sh"
